[package]
name = "junkiejoe/eventsystem"
description = "An event system for scriptable events, and input sevents."
version = "0.1.0"
license = "MIT"
authors = ["junkiejoe"]
registry = "https://github.com/junkiejoe/EventSystem"
realm = "shared"

[dependencies]
Typeforge = "cameronpcampbell/typeforge@2.1.0"